"""add ai_usages table

Revision ID: 188ae75dee9a
Revises: ee8e4ea276a2
Create Date: 2026-07-24 12:40:33.747567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '188ae75dee9a'
down_revision: Union[str, Sequence[str], None] = 'ee8e4ea276a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_usages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usages_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_usages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usages_user_id'))

    op.drop_table('ai_usages')
    # ### end Alembic commands ###
