"""add status to posts

Revision ID: 9e750b8283be
Revises: 4397d31e8bf4
Create Date: 2026-07-31 09:36:52.788260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e750b8283be'
down_revision: Union[str, Sequence[str], None] = '4397d31e8bf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('draft', 'published', name='poststatus'), nullable=False, server_default='published'))
        batch_op.create_index(batch_op.f('ix_posts_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_status'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
