"""add post_translations table, remove podcast fields from posts

Revision ID: a5eec79ceddb
Revises: 5134b84f6417
Create Date: 2026-08-04 12:26:51.321807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5eec79ceddb'
down_revision: Union[str, Sequence[str], None] = '5134b84f6417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('translated_title', sa.String(), nullable=True),
    sa.Column('translated_content', sa.String(), nullable=True),
    sa.Column('translation_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='translationstatus'), nullable=False),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('podcast_status', sa.Enum('none', 'pending', 'processing', 'completed', 'failed', name='podcaststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_translations_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_translations')),
    sa.UniqueConstraint('post_id', 'language', name='uq_post_translations_post_id_language')
    )
    with op.batch_alter_table('post_translations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_translations_post_id'), ['post_id'], unique=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('podcast_status')
        batch_op.drop_column('audio_url')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_url', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('podcast_status', sa.VARCHAR(length=10), server_default=sa.text("'none'"), nullable=False))

    with op.batch_alter_table('post_translations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_translations_post_id'))

    op.drop_table('post_translations')
    # ### end Alembic commands ###
