TOPICS = [
    "Technology",
    "Programming",
    "Artificial Intelligence",
    "Startups",
    "Business",
    "Entrepreneurship",
    "Productivity",
    "Career",
    "Education",
    "Science",
    "Data Science",
    "Cybersecurity",
    "Web Development",
    "Mobile Development",
    "Cloud Computing",
    "Design",
    "UI/UX",
    "Marketing",
    "Finance",
    "Investing",
    "Cryptocurrency",
    "Economics",
    "Psychology",
    "Self Improvement",
    "Health",
    "Fitness",
    "Nutrition",
    "Lifestyle",
    "Travel",
    "Food",
    "Books",
    "Movies",
    "Music",
    "Gaming",
    "Sports",
    "History",
    "Philosophy",
    "Politics",
    "Environment",
    "Culture"
]